<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>..\..\Presentation\Nop.Web\Plugins\Nop.Plugin.NopStation.OrderPdfDesigner</OutputPath>
    <Version>4.70.1.0</Version>
    <Authors>Nop-Station Team</Authors>
    <Company>Nop-Station</Company>
    <AssemblyVersion>4.70.1.0</AssemblyVersion>
    <FileVersion>4.70.1.0</FileVersion>
    <Product>Order PDF Designer</Product>
    <NeutralLanguage>en</NeutralLanguage>
    <OutDir>$(OutputPath)</OutDir>
    <Description>Provides a fully-editable Order PDF template with token support for generating customized order PDFs.</Description>
    <Copyright>Nop-Station Team</Copyright>
    <PackageTags>NopStation,OrderPDF,PDF,Invoice,NopCommerce,Plugin</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj">
      <Private>false</Private>
      <CopyLocal>False</CopyLocal>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj">
      <Private>false</Private>
      <CopyLocal>False</CopyLocal>
    </ProjectReference>
    <ProjectReference Include="..\NopStation.Plugin.Misc.Core\NopStation.Plugin.Misc.Core.csproj">
      <Private>false</Private>
      <CopyLocal>False</CopyLocal>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>

  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />
  </Target>

</Project>
